# Generated by Django 5.0.4 on 2024-04-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={},
        ),
    ]
